# Generated by Django 4.0.5 on 2022-06-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_todolist_author_alter_todolist_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
