# Generated by Django 4.0.5 on 2022-06-19 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_todolist_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='elements',
        ),
        migrations.CreateModel(
            name='ListElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.TextField()),
                ('listId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.todolist')),
            ],
        ),
    ]
