# Generated by Django 4.0.5 on 2022-06-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_remove_todolist_elements_listelements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listelements',
            name='element',
            field=models.CharField(max_length=500),
        ),
    ]
