# Generated by Django 4.0.5 on 2022-06-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_alter_listelements_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='listelements',
            name='deadLine',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listelements',
            name='mark_as_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listelements',
            name='reminder',
            field=models.BooleanField(default=False),
        ),
    ]
